---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-16.04
  - name: centos-6.7
  - name: fedora-23

suites:
  - name: default
    run_list:
      - recipe[php-fpm::default]
    attributes:
      php-fpm:
        pools:
          - name: web
            listen: '127.0.0.1:9081'
